defaults:
  - _self_
  - config: base
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled

hydra:  
  output_subdir: null  
  run:  
    dir: .

gene_name: Hole
ORF: Hole
img_idx: 10 
bs: 500
exam_bs: 5 
balance_fac: 0.25
balance_fac_cat: 0.5
split_stage: 2