defaults:
  - _self_
  - config: base
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled

hydra:  
  output_subdir: null  
  run:  
    dir: .

ORF: Hole
bs: 500
exam_bs: 5
method: structure